const store={get:()=>JSON.parse(localStorage.getItem('urbexUploads')||'[]'),set:v=>localStorage.setItem('urbexUploads',JSON.stringify(v))};
const progressUser={get:()=>JSON.parse(localStorage.getItem('urbexUser')||'{"xp":120,"level":2}')};
function initTheme(){const saved=localStorage.getItem('urbexTheme')||'dark';document.documentElement.dataset.theme=saved;const header=document.querySelector('.topbar');if(!header)return;const button=document.createElement('button');button.className='theme-toggle';button.type='button';button.title='Hell- oder Dunkelmodus wechseln';button.innerHTML=`<span class="theme-glyph">${saved==='dark'?'☀︎':'☾'}</span>`;button.onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('urbexTheme',next);button.classList.remove('is-switching');void button.offsetWidth;button.classList.add('is-switching');button.innerHTML=`<span class="theme-glyph">${next==='dark'?'☀︎':'☾'}</span>`};header.append(button)}
function statusLabel(s){return s==='approved'?'Freigegeben':s==='rejected'?'Abgelehnt':'Wartet auf Prüfung'}
function renderProfile(){const root=document.querySelector('#my-uploads');if(!root)return;const u=store.get();root.innerHTML=u.length?u.map(x=>`<div class="upload-row"><img src="${x.url}" alt="Upload"><div><b>${x.spot}</b><p>${statusLabel(x.status)}</p></div><span class="status ${x.status}">${statusLabel(x.status)}</span></div>`).join(''):'<p class="muted">Du hast noch keine Fotos eingereicht.</p>'}
function renderAdmin(){const root=document.querySelector('#moderation-list');if(!root)return;let u=store.get(), open=u.filter(x=>x.status==='pending');document.querySelector('#pending-count').textContent=open.length;root.innerHTML=open.length?open.map(x=>`<article class="moderation-card"><img src="${x.url}" alt="Eingereichtes Foto"><div><p class="eyebrow">EINGEREICHT VON FELIX S.</p><h2>${x.spot}</h2><p class="muted">${x.note||'Kein Kommentar hinzugefügt.'}</p><div class="actions"><button class="button primary small" onclick="moderate('${x.id}','approved')">✓ Freigeben</button><button class="button danger small" onclick="moderate('${x.id}','rejected')">✕ Ablehnen</button></div></div></article>`).join(''):'<div class="empty">✓ Keine Fotos warten auf Prüfung.</div>'}
function moderate(id,status){const u=store.get().map(x=>x.id===id?{...x,status}:x);store.set(u);renderAdmin()}
function renderReports(){const content=document.querySelector('.moderation-list');if(!content)return;const reports=JSON.parse(localStorage.getItem('urbexReports')||'[]');const section=document.querySelector('#report-review')||document.createElement('section');section.id='report-review';section.className='report-review panel-card';section.innerHTML=`<div class="section-head"><h2>Spot-Meldungen</h2><span>${reports.filter(r=>r.status==='pending').length} offen</span></div>`+(reports.length?reports.map(r=>`<div class="report-row"><div><b>${r.reason}</b><p>${r.note||'Keine weitere Erläuterung.'}</p></div><button class="button small" onclick="resolveReport('${r.id}')">Erledigt</button></div>`).join(''):'<p class="muted">Keine Meldungen vorhanden.</p>');content.after(section)}
function resolveReport(id){const reports=JSON.parse(localStorage.getItem('urbexReports')||'[]').map(r=>String(r.id)===String(id)?{...r,status:'resolved'}:r);localStorage.setItem('urbexReports',JSON.stringify(reports));renderReports()}
function renderNotifications(){const root=document.querySelector('#dynamic-notifications');if(!root)return;const done=store.get().filter(x=>x.status!=='pending');const subscriptions=JSON.parse(localStorage.getItem('urbexSubscriptions')||'[]');const subscriptionNotes=subscriptions.map(()=>`<div class="notification"><span>🔔</span><div><b>Spot-Benachrichtigungen sind aktiv</b><p>Du wirst über neue Aktivitäten an beobachteten Spots informiert.</p><small>Aktiv</small></div></div>`).join('');root.innerHTML=done.map(x=>`<div class="notification"><span>${x.status==='approved'?'✓':'×'}</span><div><b>Dein Foto wurde ${x.status==='approved'?'freigegeben':'abgelehnt'}</b><p>${x.spot}</p><small>Gerade eben</small></div></div>`).join('')+subscriptionNotes}
function renderProgress(){const user=progressUser.get(), names={1:'Neuling',2:'Entdecker',3:'Vertrauenswürdig',5:'Scout'}, next=user.level===1?100:user.level===2?250:user.level===3?700:1000, previous=user.level===1?0:user.level===2?100:user.level===3?250:700, pct=Math.min(100,Math.round((user.xp-previous)/(next-previous)*100));const profile=document.querySelector('.profile-head');if(profile){const status=document.createElement('div');status.className='profile-progress';status.innerHTML=`<a href="level.html"><b>${names[user.level]} · Level ${user.level}</b></a><span>${user.xp} / ${next} XP</span><div class="xp-track"><i style="width:${pct}%"></i></div>`;profile.append(status)}const title=document.querySelector('#level-name');if(title){title.textContent=`${names[user.level]} · Level ${user.level}`;document.querySelector('#xp-text').textContent=`${user.xp} / ${next} XP`;document.querySelector('#xp-bar').style.width=`${pct}%`}}
document.addEventListener('DOMContentLoaded',()=>{initTheme();renderProfile();renderAdmin();renderReports();renderNotifications();renderProgress()});
