const store={get:()=>JSON.parse(localStorage.getItem('urbexUploads')||'[]'),set:v=>localStorage.setItem('urbexUploads',JSON.stringify(v))};
const progressUser={get:()=>JSON.parse(localStorage.getItem('urbexUser')||'{"xp":200,"level":2}')};
function initTheme(){const saved=localStorage.getItem('urbexTheme')||'dark';document.documentElement.dataset.theme=saved;const header=document.querySelector('.topbar');if(!header)return;const button=document.createElement('button');button.className='theme-toggle';button.type='button';button.title='Hell- oder Dunkelmodus wechseln';button.innerHTML=`<span class="theme-glyph">${saved==='dark'?'☀︎':'☾'}</span>`;button.onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('urbexTheme',next);button.classList.remove('is-switching');void button.offsetWidth;button.classList.add('is-switching');button.innerHTML=`<span class="theme-glyph">${next==='dark'?'☀︎':'☾'}</span>`};header.append(button)}
function statusLabel(s){return s==='approved'?'Freigegeben':s==='rejected'?'Abgelehnt':'Wartet auf Prüfung'}
function renderProfile(){const root=document.querySelector('#my-uploads');if(!root)return;const u=store.get();root.innerHTML=u.length?u.map(x=>`<div class="upload-row"><img src="${x.url}" alt="Upload"><div><b>${x.spot}</b><p>${statusLabel(x.status)}</p></div><span class="status ${x.status}">${statusLabel(x.status)}</span></div>`).join(''):'<p class="muted">Du hast noch keine Fotos eingereicht.</p>'}
function renderSavedSpots(){const anchor=document.querySelector('.two-cols');if(!anchor)return;const saved=JSON.parse(localStorage.getItem('urbexSavedSpots')||'[]');let section=document.querySelector('#saved-spots');if(!section){section=document.createElement('section');section.id='saved-spots';section.className='panel-card saved-spots';anchor.after(section)}section.innerHTML=`<div class="section-head"><h2>Gespeicherte Spots</h2><a href="karte.html">Karte öffnen</a></div>`+(saved.length?saved.map(spot=>`<a class="saved-spot" href="karte.html"><img src="${spot.image}" alt=""><span><b>${spot.name}</b><small>${spot.category}</small></span><em>★</em></a>`).join(''):'<p class="muted">Noch keine Spots gespeichert.</p>')}
function renderAdmin(){const root=document.querySelector('#moderation-list');if(!root)return;let u=store.get(), open=u.filter(x=>x.status==='pending');document.querySelector('#pending-count').textContent=open.length;root.innerHTML=open.length?open.map(x=>`<article class="moderation-card"><img src="${x.url}" alt="Eingereichtes Foto"><div><p class="eyebrow">EINGEREICHT VON FELIX S.</p><h2>${x.spot}</h2><p class="muted">${x.note||'Kein Kommentar hinzugefügt.'}</p><div class="actions"><button class="button primary small" onclick="moderate('${x.id}','approved')">✓ Freigeben</button><button class="button danger small" onclick="moderate('${x.id}','rejected')">✕ Ablehnen</button></div></div></article>`).join(''):'<div class="empty">✓ Keine Fotos warten auf Prüfung.</div>'}
function moderate(id,status){const u=store.get().map(x=>x.id===id?{...x,status}:x);store.set(u);renderAdmin()}
function renderReports(){const content=document.querySelector('.moderation-list');if(!content)return;const reports=JSON.parse(localStorage.getItem('urbexReports')||'[]');const section=document.querySelector('#report-review')||document.createElement('section');section.id='report-review';section.className='report-review panel-card';section.innerHTML=`<div class="section-head"><h2>Spot-Meldungen</h2><span>${reports.filter(r=>r.status==='pending').length} offen</span></div>`+(reports.length?reports.map(r=>`<div class="report-row"><div><b>${r.reason}</b><p>${r.note||'Keine weitere Erläuterung.'}</p></div><button class="button small" onclick="resolveReport('${r.id}')">Erledigt</button></div>`).join(''):'<p class="muted">Keine Meldungen vorhanden.</p>');content.after(section)}
function resolveReport(id){const reports=JSON.parse(localStorage.getItem('urbexReports')||'[]').map(r=>String(r.id)===String(id)?{...r,status:'resolved'}:r);localStorage.setItem('urbexReports',JSON.stringify(reports));renderReports()}
const members=[{username:'mara_urbex',name:'Mara Keller',flag:'🇩🇪',avatar:'MK',level:18},{username:'jonas_roam',name:'Jonas Roth',flag:'🇦🇹',avatar:'JR',level:12},{username:'lena_lost',name:'Lena Weber',flag:'🇨🇭',avatar:'LW',level:27}];
const accessCfg={get:()=>({beginner:0,advanced:10,full:25,...JSON.parse(localStorage.getItem('urbexAccessSettings')||'{}')}),set:v=>localStorage.setItem('urbexAccessSettings',JSON.stringify(v))};
function renderAccessAdmin(){const target=document.querySelector('.moderation-list');if(!target)return;const cfg=accessCfg.get();const section=document.querySelector('#access-admin')||document.createElement('section');section.id='access-admin';section.className='panel-card access-admin';section.innerHTML=`<div class="section-head"><h2>Spot-Sichtbarkeit nach Level</h2><span>Admin</span></div><form class="access-form" onsubmit="saveAccessSettings(event)"><label>Grundlegende Spots <input id="access-beginner" type="number" min="0" value="${cfg.beginner}"></label><label>Weitere Spots <input id="access-advanced" type="number" min="0" value="${cfg.advanced}"></label><label>Alle Spots <input id="access-full" type="number" min="0" value="${cfg.full}"></label><button class="button primary small">Speichern</button></form><p class="muted">Die Werte werden später serverseitig je Spot-Typ geprüft.</p>`;target.after(section)}
function saveAccessSettings(e){e.preventDefault();accessCfg.set({beginner:+document.querySelector('#access-beginner').value,advanced:+document.querySelector('#access-advanced').value,full:+document.querySelector('#access-full').value});renderAccessAdmin()}
function renderPrivateMaps(){const root=document.querySelector('#private-map-area');if(!root)return;const user=progressUser.get();const maps=JSON.parse(localStorage.getItem('urbexPrivateMaps')||'[]');if(user.level<10){root.innerHTML=`<div class="empty">🔒 Private Karten werden ab Level 10 freigeschaltet. Dein aktuelles Level: ${user.level}.</div>`;return}root.innerHTML=`<button class="button primary" onclick="createPrivateMap()">＋ Private Karte erstellen</button><div class="private-map-list">${maps.length?maps.map(m=>`<article class="panel-card"><div class="section-head"><h2>${m.name}</h2><span>${m.invites.length} eingeladen</span></div><div class="invite-entry"><input placeholder="Username suchen" oninput="suggestMember(this, '${m.id}')"><div id="suggest-${m.id}" class="member-suggestions"></div></div><div class="invited-members">${m.invites.map(u=>`<span>${u.avatar} ${u.name}</span>`).join('')||'<small>Noch niemand eingeladen.</small>'}</div></article>`).join(''):'<p class="muted">Noch keine private Karte erstellt.</p>'}</div>`}
function createPrivateMap(){const name=prompt('Name der privaten Karte:');if(!name)return;const maps=JSON.parse(localStorage.getItem('urbexPrivateMaps')||'[]');maps.push({id:String(Date.now()),name,invites:[]});localStorage.setItem('urbexPrivateMaps',JSON.stringify(maps));renderPrivateMaps()}
function suggestMember(input,mapId){const box=document.querySelector(`#suggest-${mapId}`),query=input.value.toLowerCase();box.innerHTML=query?members.filter(m=>m.username.includes(query)||m.name.toLowerCase().includes(query)).map(m=>`<button type="button" onclick="inviteMember('${mapId}','${m.username}')"><i>${m.avatar}</i><span>${m.name}<small>@${m.username} · ${m.flag}</small></span></button>`).join(''):''}
function inviteMember(mapId,username){const maps=JSON.parse(localStorage.getItem('urbexPrivateMaps')||'[]');const member=members.find(m=>m.username===username);const map=maps.find(m=>m.id===mapId);if(member&&!map.invites.some(m=>m.username===username))map.invites.push(member);localStorage.setItem('urbexPrivateMaps',JSON.stringify(maps));renderPrivateMaps()}
function renderMemberProfile(){const root=document.querySelector('#member-profile');if(!root)return;const user=members.find(m=>m.username===new URLSearchParams(location.search).get('u'))||members[0];root.innerHTML=`<section class="profile-head"><div class="profile-avatar">${user.avatar}</div><div><p class="eyebrow">COMMUNITY-MITGLIED</p><h1>${user.name}</h1><p class="muted">@${user.username} · ${user.flag}</p></div><a class="button small" href="chat.html">Nachricht schreiben</a></section><section class="stats"><div><b>Level ${user.level}</b><span>Explorer</span></div><div><b>37</b><span>Beiträge</span></div><div><b>14</b><span>Spots gespeichert</span></div></section>`}
function renderChat(){const root=document.querySelector('#chat-area');if(!root)return;const groups=JSON.parse(localStorage.getItem('urbexGroups')||'[]');root.innerHTML=`<div class="chat-layout"><aside><button class="button primary small" onclick="createGroup()">＋ Gruppe erstellen</button><h3>Direktnachrichten</h3>${members.map(m=>`<button class="chat-group" onclick="openDirect('${m.username}')">${m.flag} ${m.name}<small>@${m.username}</small></button>`).join('')}<h3>Gruppen</h3>${groups.map(g=>`<button class="chat-group" onclick="openGroup('${g.id}')"># ${g.name}<small>${g.members.length} Mitglieder</small></button>`).join('')||'<p class="muted">Noch keine Gruppen.</p>'}</aside><section id="chat-thread" class="panel-card"><p class="muted">Wähle einen Kontakt oder erstelle eine Gruppe. Gruppen-Einladungen müssen angenommen werden.</p></section></div>`}
function openDirect(username){const member=members.find(m=>m.username===username),key=`urbexDM-${username}`,messages=JSON.parse(localStorage.getItem(key)||'[]'),thread=document.querySelector('#chat-thread');thread.innerHTML=`<div class="section-head"><h2>${member.flag} ${member.name}</h2><a class="button small" href="nutzer.html?u=${username}">Profil</a></div><div class="chat-messages">${messages.map(m=>`<p><b>${m.author}</b> ${m.text}</p>`).join('')||'<p class="muted">Noch keine Nachrichten.</p>'}</div><form class="comment-form" onsubmit="sendDirect(event,'${username}')"><input id="direct-message" placeholder="Nachricht schreiben"><button>➤</button></form>`}
function sendDirect(e,username){e.preventDefault();const field=document.querySelector('#direct-message'),text=field.value.trim();if(!text)return;const key=`urbexDM-${username}`,messages=JSON.parse(localStorage.getItem(key)||'[]');messages.push({author:'Felix S.',text});localStorage.setItem(key,JSON.stringify(messages));openDirect(username)}
function createGroup(){const name=prompt('Gruppenname:');if(!name)return;const groups=JSON.parse(localStorage.getItem('urbexGroups')||'[]');groups.push({id:String(Date.now()),name,members:[{username:'felix',name:'Felix S.'}],requests:[],messages:[]});localStorage.setItem('urbexGroups',JSON.stringify(groups));renderChat()}
function openGroup(id){const group=JSON.parse(localStorage.getItem('urbexGroups')||'[]').find(g=>g.id===id),thread=document.querySelector('#chat-thread');thread.innerHTML=`<div class="section-head"><h2># ${group.name}</h2><button class="button small" onclick="requestGroupInvite('${id}')">Mitglied einladen</button></div>${group.requests.length?`<div class="group-requests"><b>Offene Anfragen</b>${group.requests.map(m=>`<p>${m.name} <button class="button small" onclick="acceptGroupRequest('${id}','${m.username}')">Annehmen</button></p>`).join('')}</div>`:''}<div class="chat-messages">${group.messages.map(m=>`<p><b>${m.author}</b> ${m.text}</p>`).join('')||'<p class="muted">Noch keine Nachrichten.</p>'}</div><form class="comment-form" onsubmit="sendGroupMessage(event,'${id}')"><input id="group-message" placeholder="Nachricht schreiben"><button>➤</button></form>`}
function requestGroupInvite(id){const name=prompt('Username einladen:');const groups=JSON.parse(localStorage.getItem('urbexGroups')||'[]'),group=groups.find(g=>g.id===id),member=members.find(m=>m.username===name);if(member){group.requests.push(member);localStorage.setItem('urbexGroups',JSON.stringify(groups));alert(`Anfrage an ${member.name} gesendet. Sie muss angenommen werden.`)}}
function acceptGroupRequest(id,username){const groups=JSON.parse(localStorage.getItem('urbexGroups')||'[]'),group=groups.find(g=>g.id===id),member=group.requests.find(m=>m.username===username);if(member){group.members.push(member);group.requests=group.requests.filter(m=>m.username!==username);localStorage.setItem('urbexGroups',JSON.stringify(groups));openGroup(id)}}
function sendGroupMessage(e,id){e.preventDefault();const field=document.querySelector('#group-message'),text=field.value.trim();if(!text)return;const groups=JSON.parse(localStorage.getItem('urbexGroups')||'[]'),group=groups.find(g=>g.id===id);group.messages.push({author:'Felix S.',text});localStorage.setItem('urbexGroups',JSON.stringify(groups));openGroup(id)}
function renderNotifications(){const root=document.querySelector('#dynamic-notifications');if(!root)return;const done=store.get().filter(x=>x.status!=='pending');const subscriptions=JSON.parse(localStorage.getItem('urbexSubscriptions')||'[]');const subscriptionNotes=subscriptions.map(()=>`<div class="notification"><span>🔔</span><div><b>Spot-Benachrichtigungen sind aktiv</b><p>Du wirst über neue Aktivitäten an beobachteten Spots informiert.</p><small>Aktiv</small></div></div>`).join('');root.innerHTML=done.map(x=>`<div class="notification"><span>${x.status==='approved'?'✓':'×'}</span><div><b>Dein Foto wurde ${x.status==='approved'?'freigegeben':'abgelehnt'}</b><p>${x.spot}</p><small>Gerade eben</small></div></div>`).join('')+subscriptionNotes}
function renderProgress(){const user=progressUser.get(), names={0:'Gast',1:'Neuling',2:'Entdecker',3:'Vertrauenswürdig',5:'Scout',10:'Kartograf',25:'Kurator'}, next=user.level<10?10:user.level<25?25:50, pct=Math.min(100,Math.round(user.level/next*100));const profile=document.querySelector('.profile-head');if(profile){const status=document.createElement('div');status.className='profile-progress';status.innerHTML=`<a href="level.html"><b>${names[user.level]||'Explorer'} · Level ${user.level}</b></a><a href="level.html">${user.xp} XP · Levelvorteile ansehen</a><div class="xp-track"><i style="width:${pct}%"></i></div>`;profile.append(status)}const title=document.querySelector('#level-name');if(title){title.textContent=`${names[user.level]||'Explorer'} · Level ${user.level}`;document.querySelector('#xp-text').textContent=`${user.xp} XP`;document.querySelector('#xp-bar').style.width=`${pct}%`;document.querySelector('.level-grid').innerHTML=`<article class="level-card"><b>LEVEL 0</b><h2>Besucher</h2><p>Öffentliche Basis-Spots ansehen und speichern.</p></article><article class="level-card"><b>LEVEL 10</b><h2>Kartograf</h2><p>Weitere Spots sehen und private Karten für dich und Eingeladene erstellen.</p></article><article class="level-card"><b>LEVEL 25</b><h2>Kurator</h2><p>Alle freigegebenen Spots sehen und höchste Vertrauensstufe erhalten.</p></article>`}}
document.addEventListener('DOMContentLoaded',()=>{initTheme();renderProfile();renderSavedSpots();renderAdmin();renderReports();renderAccessAdmin();renderNotifications();renderProgress();renderPrivateMaps();renderMemberProfile();renderChat()});
